apply plugin: 'com.android.application'

android {
    namespace = 'own.ownplanetswallpaper.ae'
    compileSdkVersion 37
    buildToolsVersion "25.0.2"
    useLibrary 'org.apache.http.legacy'
    defaultConfig {
        applicationId "own.ownplanetswallpaper.ae"
        minSdkVersion 15
        targetSdkVersion 37
        versionCode 1
        versionName "1.1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

configurations.all {
    resolutionStrategy {
        force 'androidx.vectordrawable:vectordrawable:1.1.0'
        force 'androidx.vectordrawable:vectordrawable-animated:1.1.0'
    }
}

dependencies {
    //implementation fileTree(dir: 'libs', include: ['*.jar'])
    //androidTestimplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
    //    exclude group: 'com.android.support', module: 'support-annotations'
    //})
    implementation 'com.android.support:appcompat-v7:28.0.0'
    //testimplementation 'junit:junit:4.13.2'
}
